dist: trusty
sudo: required
env:
   - SWIFT_VERSION=4.0.3
language:               node_js
node_js:
   - "node"
   - "lts/*"
   - "7"
   - "8"
before_install:
   - npm install -g npm@latest
   - npm install -g eye.js
   - sudo apt-get install python3
install:
   - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)" # Install swift
script:
   - eye # JS
   - swiftc Swift/lib.swift -o out # Swift
   - python3 Python3/decrypt.py
   - python3 Python3/encrypt.py
   - python3 Python3/vcodecs.py
notifications:
 email:                false
